# Generated by Django 5.0.6 on 2024-07-07 22:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0003_property_area_property_bedroom_property_washroom'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='rent_or_sale',
            field=models.CharField(choices=[('rent', 'Rent'), ('sale', 'Sale')], default='sale', max_length=10),
        ),
    ]
