# Generated by Django 5.0.6 on 2024-07-07 22:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0004_property_rent_or_sale'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='rent_or_sale',
            field=models.CharField(choices=[('rent', 'Rent'), ('buy', 'Buy')], default='buy', max_length=10),
        ),
    ]
