# Generated by Django 5.0.6 on 2024-07-10 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0007_property_city'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='price',
            field=models.TextField(),
        ),
    ]
