# Generated by Django 5.0.6 on 2024-10-24 17:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0008_alter_property_price'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='property',
            options={'verbose_name_plural': 'Properties'},
        ),
        migrations.AlterModelOptions(
            name='propertycategory',
            options={'verbose_name_plural': 'Property Categories'},
        ),
    ]
