# Generated by Django 5.0.6 on 2024-11-10 18:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("properties", "0010_agreement"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="agreement",
            name="user",
            field=models.ForeignKey(
                default=12,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="agreements",
                to=settings.AUTH_USER_MODEL,
            ),
            preserve_default=False,
        ),
    ]
