# Generated by Django 5.0.6 on 2024-11-27 20:46

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0010_customer_agreement'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='customer',
            unique_together={('user',)},
        ),
    ]
