# Generated by Django 5.0.6 on 2024-11-27 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0011_alter_customer_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='agreement',
            name='customer_note',
            field=models.TextField(blank=True, null=True),
        ),
    ]
