# Generated by Django 5.0.6 on 2024-12-24 19:40

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("properties", "0016_alter_payment_status"),
    ]

    operations = [
        migrations.CreateModel(
            name="UtilityBill",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "bill_type",
                    models.CharField(
                        choices=[
                            ("electricity", "Electricity"),
                            ("gas", "Gas"),
                            ("water", "Water"),
                            ("other", "Other"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "bill_amount",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=10,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                (
                    "paid_amount",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=10,
                        null=True,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                ("bill_date", models.DateField()),
                ("due_date", models.DateField()),
                ("paid_date", models.DateField(blank=True, null=True)),
                (
                    "bill_image",
                    models.ImageField(blank=True, null=True, upload_to="bills/"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "agreement",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="utility_bills",
                        to="properties.agreement",
                    ),
                ),
            ],
            options={
                "ordering": ["-bill_date"],
            },
        ),
    ]
